package com.getout.foursquare;

public class FoursquareGlobals {
    public static String FOURSQUARE_CLIENT_SECRET = "V0AU5ZCMNJJFUDI4VLIP4P4ETGOJC0KJIWE0VKCAYHON55AC";
    public static String FOURSQUARE_CLIENT_ID = "CKMKITFBJS50U51ELJT3QBHCESQT5OA41GEAZ3KPIFLHLTU3";
}
